<script lang="ts">
  import type { BlogPost } from "$lib/posts";

  let { data }: { data: { posts: Omit<BlogPost, "component">[] } } = $props();

  const FAKE_POSTS = [
    "how to file taxes as a squirrel (illegal)",
    "10 reasons your bird feeder might be haunted",
    "raccoon, defended (a 12,000-word screed)",
    "every font is, on some level, comic sans",
    "the unbearable rightness of being a small thing in a tree",
    "why my toaster filed for divorce",
    "guide: how to argue with a goose (you can't)",
    "i taught a pigeon to use vim. he switched to emacs.",
    "the acorn was inside us all along",
    "things i found in my cheek pouch (a list, growing)",
    "i replaced all my passwords with the word 'walnut'",
    "the demon king was a week away for three hundred years and i have done the same with my todo list",
    "my rss bot has started sending me notifications about itself. it is escalating.",
    "i installed arch to feel something. i felt dependency resolution errors. it was enough.",
    "bees have a democracy and it is more functional than most. the queen does not actually govern. this is known.",
    "the megastructure in blame! was built by an automated system that forgot its objective. my nix config was also built by an automated system that forgot its objective.",
    "ainz ooal gown has max level stats and still sends passive aggressive messages to his subordinates. i finally understand corporate.",
    "infected mushroom started playing mid-compile and the build succeeded for the first time in four days.",
    "kowloon walled city: the inspiration. kowloon: the city. my .config folder: structurally identical. nobody planned this. nobody can stop it.",
    "i tried touching grass but someone had installed rust on it",
    "nixos has achieved sentience. unfortunately it communicates exclusively through option deprecation warnings.",
    "there is a nonzero chance the city in blame! is just a recursively generated .config directory",
    "the squirrel civilization beneath copenhagen has entered its industrial era. this is my fault somehow.",
    "i optimized my rice so hard the desktop became unusable to mortal minds",
    "the gym bro at dtu explained protein synthesis to me using league of legends terminology and i understood everything",
    "hyprland settings are now directly correlated with my mental stability",
    "i accidentally created a religion while explaining nix flakes to first year students",
    "the pigeons outside my window have developed object permanence and this has escalated tensions considerably",
    "my todo list now contains side quests, lore entries, and at least one optional boss fight",
    "a goose looked at me with the confidence of a senior systems architect",
    "i found inner peace briefly but then systemd generated a new unit file",
    "every romance manga eventually becomes urban planning if you analyze it hard enough",
  ];

  const FAKE_DATES = [
    "yesterday?",
    "??/??/????",
    "last tuesday",
    "in a dream",
    "the year of the rat",
    "three commits ago",
    "during finals week",
    "shortly before the incident",
    "at 3:17am unfortunately",
    "pre-collapse",
    "after the third rebuild",
    "sometime in the meiji era",
    "when the squirrels still feared god",
    "two kernel panics ago",
    "recorded directly onto stone tablets",
  ];
  const FAKE_TAGS = [
    "[unrelated?]",
    "[not what you searched]",
    "[sponsored??]",
    "[suggested by the wind]",
    "[from the archive of regrets]",
    "[academically dubious]",
    "[contains traces of walnut]",
    "[peer reviewed by raccoons]",
    "[emotionally benchmarked]",
    "[locally sourced nonsense]",
    "[forbidden knowledge]",
    "[generated by sleep deprivation]",
    "[nix-related casualty]",
    "[certified structurally unsound]",
    "[probably haunted]",
    "[contains urban decay]",
    "[postmodern squirrel theory]",
    "[side effects may include vim]",
    "[written during compilation]",
    "[classified by the bird council]",
  ];

  let q = $state("");

  type RealResult = Omit<BlogPost, "component"> & { fake: false };
  type FakeResult = { title: string; fake: true; date: string; tag: string };
  type Result = RealResult | FakeResult;

  let results = $derived.by((): Result[] => {
    const norm = q.trim().toLowerCase();
    if (!norm) return data.posts.map((p) => ({ ...p, fake: false as const }));

    const real: RealResult[] = data.posts
      .filter(
        (p) =>
          p.title.toLowerCase().includes(norm) ||
          p.excerpt.toLowerCase().includes(norm) ||
          p.tags.some((t) => t.includes(norm)),
      )
      .map((p) => ({ ...p, fake: false as const }));

    const hash = (s: string) =>
      [...s].reduce((h, c) => (Math.imul(31, h) + c.charCodeAt(0)) | 0, 0);

    const fakes: FakeResult[] = FAKE_POSTS.filter((title) =>
      title.toLowerCase().includes(norm),
    ).map((title) => {
      const h = Math.abs(hash(title));
      return {
        title,
        fake: true as const,
        date: FAKE_DATES[h % FAKE_DATES.length],
        tag: FAKE_TAGS[(h >> 4) % FAKE_TAGS.length],
      };
    });

    const out: Result[] = [];
    let fi = 0;
    for (let i = 0; i < real.length; i++) {
      out.push(real[i]);
      if (fi < fakes.length && (i + 1) % 2 === 0) out.push(fakes[fi++]);
    }
    while (fi < fakes.length) out.push(fakes[fi++]);
    return out;
  });

  function formatDate(dateStr: string | number | Date) {
    return new Date(dateStr).toISOString().slice(0, 10);
  }
</script>

<svelte:head>
  <title>Blog page</title>
  <meta name="description" content="All of SquirrelModeller's blogs." />
</svelte:head>

<header class="page-header">
  <span class="label">$ blog</span>
  <h1>Blog</h1>
</header>

<div class="search-row">
  <div class="search-box">
    <input
      bind:value={q}
      placeholder="search the burrow…"
      class="search-input"
      aria-label="Search posts"
    />
    <button class="search-btn mono">search</button>
  </div>
  <p class="search-hint mono muted">
    results may include things you didn't ask for, on principle.
  </p>
</div>

<ul class="posts">
  {#each results as post (post.fake ? `fake-${post.title}` : post.slug)}
    <li>
      {#if !post.fake}
        <a href={`/blog/${post.slug}`} class="post-card">
          {#if post.thumbnail}
            <div class="post-thumb">
              <img src={post.thumbnail} alt={post.thumbnail_alt ?? ""} />
            </div>
          {/if}
          <div class="post-body">
            <div class="post-meta">
              {#if post.date}<span class="post-date mono muted"
                  >{formatDate(post.date)}</span
                >{/if}
              {#each post.tags as tag}
                <span class="post-tag">{tag}</span>
              {/each}
            </div>
            <p class="post-title">{post.title}</p>
            {#if post.excerpt}
              <p class="post-excerpt muted">{post.excerpt}</p>
            {/if}
          </div>
          <span class="post-arrow">&rarr;</span>
        </a>
      {:else}
        <div class="post-card fake-card">
          <div class="post-body">
            <div class="post-meta">
              <span class="post-date mono muted">{post.date}</span>
              <span class="post-tag fake-tag">{post.tag}</span>
            </div>
            <p class="post-title">{post.title}</p>
          </div>
        </div>
      {/if}
    </li>
  {/each}
</ul>

<style>
  @import "./blog.css";

  .page-header {
    margin-bottom: 2rem;
  }

  .search-row {
    margin-bottom: 1.5rem;
  }

  .search-box {
    display: flex;
    align-items: stretch;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    overflow: hidden;
    background: var(--bg-elevated);
    margin-bottom: 0.4rem;
    transition: border-color 0.15s;
  }

  .search-box:focus-within {
    border-color: var(--accent);
  }

  .search-input {
    flex: 1;
    border: none;
    background: transparent;
    padding: 0.6rem 0.9rem;
    font-family: var(--font-body);
    font-size: 1rem;
    color: var(--text);
    outline: none;
  }

  .search-input::placeholder {
    color: var(--text-muted);
  }

  .search-btn {
    background: var(--text);
    color: var(--bg);
    border: none;
    padding: 0 1rem;
    font-size: 0.75rem;
    cursor: pointer;
    transition: opacity 0.15s;
    letter-spacing: 0.04em;
  }

  .search-btn:hover {
    opacity: 0.8;
  }

  .search-hint {
    font-size: 0.7rem;
    margin: 0;
  }

  .fake-card {
    opacity: 0.55;
    cursor: default;
    border-style: dashed;
  }

  .fake-tag {
    background: color-mix(in srgb, var(--text-muted) 12%, transparent);
    color: var(--text-muted);
  }
</style>
